language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
#  - pip install coveralls
script:
  - python -m py_compile pywishlist.py
#  - coverage run --source=PyWishlist -m py_compile pywishlist.py

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/353f6c7d987d6bca099e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

#after_success:
#  coveralls