version: '3'
services:
  pywishlist:
    build: .
    ports:
      - "3036:80"
    volumes:
      - "${PWD}/pywishlist/static:/app/pywishlist/static"
      - "${PWD}/config/pywishlist.cfg:/app/config/pywishlist.cfg"
    environment:
      - DEBUG