version: '3'
services:
  pywishlist:
    container_name: pywishlist
    restart: unless-stopped
    build: .
    ports:
      - "3036:80"
    volumes:
      - ./pywishlist/static/img:/app/pywishlist/static/img:ro
      - ./config/pywishlist.cfg:/app/config/pywishlist.cfg:ro
    environment:
      - DEBUG:wq