version: "3"
services:
  pywishlist:
    container_name: pywishlist
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
    volumes:
      - ./pywishlist/static/img:/app/pywishlist/static/img
      - ./config:/app/config:rw
    environment:
      - DEBUG
